//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Marketing.Testing.Dal.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201603241337050_Initial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201603241337050_Initial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPiServer.Marketing.Testing.Dal.Migrations.201603241337050_Initial", typeof(_201603241337050_Initial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1c3W7jNha+X2DfQdDlIrWdDAq0gd0ik5/C2MkkiDPZxd4MaOnYISpRrkilMRb7ZL3oI+0r7JGtP5KiTElO6nSDuZiEPx95Ds/hOaQ+5r+//T7+8TkMnCeIOY3YxD0ejFwHmBf5lC0nbiIW33zn/vjDX/8yvvTDZ+chb/chbYc9GZ+4j0KsTodD7j1CSPggpF4c8WghBl4UDokfDU9Go++Hx8dDQAgXsRxnfJcwQUPY/IK/nkfMg5VISHAd+RDwrBxrZhtU5zMJga+IBxP38pbOIMYZD65J/DMInOjgHvjm/wsSuM5ZQAlOawbBwnUIY5EgAid9+oXDTMQRW85WWECC+/UKsN2CBBwyYU7L5rZyjU5SuYZlxxzKS7iIwpaAxx8yRQ3V7p3U7RaKRFVeosrFOpV6o86Je/Yx1ZvrqEOdngdx2mynrgdbyMEW6MjJqo4KO0FzSv8dOedJIJIYJgwSEZPgyLlN5gH1/g7r++hnYBOWBEF1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
