//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Marketing.Testing.Dal.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201606291147071_Initial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201606291147071_Initial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPiServer.Marketing.Testing.Dal.Migrations.201606291147071_Initial", typeof(_201606291147071_Initial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1cW2/juBV+L9D/IOipLbJWMvOyDexdZHJZGJ1MgnEmLfoyoKVjh1iK8pJU1kbRX9aH/qT+hR7ZupCUKEuyN0jaQR5i8/KR5/DwXHhO8p9//Xv84zpm3jMISRM+8c9Gp74HPEwiypcTP1WL7773f/zh978bX0fx2nssxr3PxuFMLif+k1Kr8yCQ4RPERI5iGopEJgs1CpM4IFESvDs9/XNwdhYAQviI5XnjzylXNIbtF/x6mfAQViol7DaJgMm8HXtmW1TvE4lBrkgIE//6ns5A4I5Ht0T8DAo3OnoAuf19RZjvXTBKcFszYAvfI5wniijc9PkXCTMlEr6crbCBsIfNCnDcgjAJOTHn1fCudJ2+y+gKqokFVJhKlcQ9Ac/e54wK7OmD2O2XjERWXiPL1SajesvOiY/cuviQsc737NXOL5nIRu5l92iHuj22UQl44uVDTkqRQcnKfk68y5SpVMCEQ6oEYSfefTpnNPwLbB6Sn4FPeMqY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
