//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Marketing.Testing.Dal.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201609091719244_Initial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201609091719244_Initial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPiServer.Marketing.Testing.Dal.Migrations.201609091719244_Initial", typeof(_201609091719244_Initial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1cW2/jNhZ+X6D/QdDT7iK1kpmXNrBbZJykMHYyCcaZ7GJfBrR07BClKFekUhtFf1kf+pP2L+yRrQtJibIubpC0gzzE5uUjz+HhufCc5H+//T7+fhMy5wliQSM+cc9Gp64D3I8CylcTN5HLr79xv//uq7+Nr4Jw4zzk496m43AmFxP3Ucr1uecJ/xFCIkYh9eNIREs58qPQI0HkvTk9/dY7O/MAIVzEcpzxx4RLGsLuC36dRtyHtUwIu4kCYCJrx575DtX5QEIQa+LDxL26o3OIccejGxL/CBI3OroHsft9SZjrXDBKcFtzYEvXIZxHkkjc9PknAXMZR3w1X2MDYffbNeC4JWECMmLOy+Ft6Tp9k9LllRNzKD8RMgo7Ap69zRjlmdN7sdstGImsvEKWy21K9Y6dExe5dfEuZZ3rmKudT1mcjjzI7tEedXdsowLwxMmGnBQig5KV/pw404TJJIYJh0TGhJ04d8mCUf9fsL2PfgQ+4Qlj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
