//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Marketing.Testing.Dal.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201604221951354_Initial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201604221951354_Initial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPiServer.Marketing.Testing.Dal.Migrations.201604221951354_Initial", typeof(_201604221951354_Initial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1cW28bNxZ+X2D/w2AeF67GTlCgNaQWjmwHwsaxETneoi8BNXMkE+FwVJLjWCj2l+1Df1L/wp6R5kJyLpqLYthtkIfYvHzkufBc5pzkz//9Mf75MWTOAwhJIz5xT0bHrgPcjwLKVxM3VsvvfnB//umf/xhfBOGjc5ete52sw51cTtx7pdannif9ewiJHIXUF5GMlmrkR6FHgsh7dXz8o3dy4gFCuIjlOOMPMVc0hO0v+Os04j6sVUzYVRQAk+k4zsy3qM57EoJcEx8m7sUNnYPAG4+uiPgMCi86ugW5/fucMNc5Y5TgtebAlq5DOI8UUXjp048S5kpEfDVf4wBht5s14LolYRJSYk6L5W3pOn6V0OUVGzMoP5YqCjsCnrxOGeXZ23ux280Ziay8QJarTUL1lp0TF7l19iZhnevYp51OmUhW7mX3aIe6FdsoBzxy0iVHucqgZiV/jpxpzFQsYMIhVoKwI+cmXjDq/xs2t9Fn4BMeM6bf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
