//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("2.4.2")]
[assembly: AssemblyInformationalVersion("2.4.2-bugfix-000000")]
[assembly: AssemblyCopyright("Copyright (c) Episerver 2020")]

