//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Marketing.KPI.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201603241331322_Initial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201603241331322_Initial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPiServer.Marketing.KPI.Migrations.201603241331322_Initial", typeof(_201603241331322_Initial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAM1Xy27bOBTdDzD/IHA1A6Ri0m46gdwitZPCSJ0YVdo9LV05RPlQSSqwv20W80nzC3Opt+VH7CAYFAECirz38Nw3/e/f/0QfV1IET2As12pELsJzEoBKdMrVckQKl715Tz5++P236DqVq+B7I/fOy6GmsiPy6Fx+SalNHkEyG0qeGG115sJES8pSTd+en/9FLy4oIARBrCCIvhbKcQnlB36OtUogdwUTM52CsPU+nsQlanDHJNicJTAi13Meg0HG4YyZH+CQaHg7n4YTJkhwJThDSjGIjARMKe2YQ8KX3yzEzmi1jHPcYOJhnQPKZUxYqA257MSPten8rbeJdooNVFJYp+WJgBfvaifRofqLXE1aJ6Ibr9Hdbu2tLl05Irc5J8HwnsuxMF7moJPDMkQhApwFuHXWJgXmjv87C8aFcIWBkYLCGSbOgnmxEDy5hfWD/gFqpAoh+uyQH55tbODW3OgcjFt/hazmPE1JQDf16FCxVevpVCZ9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
