//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Marketing.KPI.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201604051658334_Initial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201604051658334_Initial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPiServer.Marketing.KPI.Migrations.201604051658334_Initial", typeof(_201604051658334_Initial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAM1X227bOBB9X2D/QeDTLpCKSfvSDeQWWTkpjNSJUaV9p6WRQ5QXlaQC+9v6sJ+0v7BD62r5UjsNioUBQxrOHJ4ZzoX69/s/0fulFMETGMu1GpGL8JwEoFKdcbUYkdLlr96S9+9+/y26zuQy+NLovfF6aKnsiDw6V1xSatNHkMyGkqdGW527MNWSskzT1+fnf9GLCwoIQRArCKJPpXJcwvoFX2OtUihcycRUZyBsLceVZI0a3DEJtmApjMj1jCdgkHE4ZeYrOCQa3s4m4ZgJElwJzpBSAiInAVNKO+aQ8OVnC4kzWi2SAgVMPKwKQL2cCQu1I5ed+rE+nb/2PtHOsIFKS+u0PBHw4k0dJDo0f1aoSRtEDOM1htutvNfrUI4IRuu24CQYbnUZC+PVDsY5XJ9SWGGcBSg9a1MDM8j/zoK4FK40MFJQOsPEWTAr54Knt7B60F9BjVQpRJ8jssS1DQGKZkYXYNzqE+Q180lGArppR4eGrVnP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
