//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("2.5.3")]
[assembly: AssemblyInformationalVersion("2.5.3-bugfix-000000")]
[assembly: AssemblyCopyright("Copyright (c) Episerver 2020")]

